name: {{name}}
version: '0.1.0'
category: {{category}}{{^category}}Web{{/category}}
author: {{author-name}}{{^author-name}}Author name here{{/author-name}}
maintainer: {{author-email}}{{^author-email}}example@example.com{{/author-email}}
copyright: {{copyright}}{{^copyright}}{{year}}{{^year}}2023{{/year}} {{author-name}}{{^author-name}}Author name here{{/author-name}}{{/copyright}}
license: BSD3
github: {{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >=4.9 && <5


library:
  source-dirs:        src
  exposed-modules:    {{name}}{{^name}}Lib{{/name}}

executable:
  {{name}}:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{name}}

tests:
  {{name}}-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{name}}
      - hspec
      - QuickCheck
    build-tools: hspec-discover

benchmarks:
  {{name}}-test:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - {{name}}
      - criterion